version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/code
    environment:
      node_env: development
    depends_on:
      - "db"

  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      database_host: localhost
      postgres_user: ${postgres_user}
      postgres_password: ${postgres_password}
      postgres_db: ${postgres_db}
    volumes:
      - db-data:/foo

volumes:
  db-data:
