version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    environment:
      NODE_ENV: development

  db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESS_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/foo

volumes:
  db-data:
