# on:
#   push:
#     branches:
#       - main
#       - kubernetes

# jobs:
#   deploy-to-cluster:
#     runs-on: ubuntu-latest
#     steps:
#       - name: deploy to cluster
#         uses: actions-hub/kubectl@master
#         env:
#           KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
#           KUBE_CONTEXT: ${{ secrets.KUBE_CONTEXT }}
#         with:
#           args: get pods

name: Deploy App on GKE cluster.
on:
  push:
    branches: [kubernetes]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubectl - Google Cloud GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: dulcet-bucksaw-350506
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLUSTER_NAME: node-server
          ZONE_NAME: europe-west1
        with:
          args: get pods
