name: Docker Image CI

on:
  push:
    branches: [main, 58-deploy-pipeline]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag domingocast/nodeserver:1.0
      - name: Push docker image
        run: docker push my-image-name:$(date +%s)
